basePath: /api/v1
definitions:
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.SendVerifyRequest:
    properties:
      email:
        type: string
    type: object
  request.UserCreateRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  response.JSONBadRequestResult:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: boolean
    type: object
  response.JSONSuccessResult:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  response.JSONUnauthorizedResult:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
  description: This is a Capstone application
  title: Capstone application Documentation
  version: "2.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login for get JWT token
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONSuccessResult'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.JSONBadRequestResult'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.JSONUnauthorizedResult'
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Register for create new user
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONSuccessResult'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.JSONBadRequestResult'
      summary: Register new user
      tags:
      - Auth
  /users:
    get:
      consumes:
      - application/json
      description: Get all list users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONSuccessResult'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.JSONBadRequestResult'
      security:
      - JWT: []
      summary: Get all list users
      tags:
      - User
  /verify/send:
    post:
      consumes:
      - application/json
      description: Send verification to email user
      parameters:
      - description: required
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendVerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.JSONSuccessResult'
            - properties:
                data:
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.JSONBadRequestResult'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.JSONBadRequestResult'
      summary: Send verify email
      tags:
      - Auth
schemes:
- http
- https
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
